version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
        VITE_FIREBASE_VAPID_KEY: ${VITE_FIREBASE_VAPID_KEY}
        VITE_BACKEND_URL: http://backend:5000
        VITE_SOCKET_URL: http://backend:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
